language: go
go:
 - 1.7.3

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/tools/godep

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - godep restore

script:
 - cd handlers
 - $HOME/gopath/bin/goveralls -service=travis-ci
